myapps/about/urls.py
from django.urls import path

from . import views


app_name = 'about'
urlpatterns = [
    # path('structure/', views.employees, name='structure'),
    path('structure/', views.structure, name='structure'),
    path('vacancies/', views.vacancies, name='vacancies'),
    path('documents/', views.documents, name='documents'),
    path('projects/', views.projects, name='projects'),
    path('history/', views.history, name='history'),
    # path('documents/<int:year>-<int:month>-<int:day>/<slug:slug>.docx',
    #      views.documents, name='documents'),

    # path('subscribe/', views.subscribe, name='subscribe'),
    # path('advertising/', views.advertising, name='advertising'),
    # path('announcing/', views.announcing, name='announcing'),
    # path('contacts/', views.contacts, name='contacts'),
]

myapps/about/templates/advertising.html
{% extends 'base.html' %}
{% block title %}Реклама / ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета "Селький труженик"{% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><i class="fas fa-home"></i> Главная</li>
    <li class="breadcrumb-item active" aria-current="page">Реклама</li>
  </ol>
</nav>
{% endblock breadcrumb %}

{% block open_graph %}
    <meta property="og:type" content="website" />
    <meta property="og:locale" content="ru_RU">
    <meta property="og:title" content="Реклама на ЯЛ ӖҪЧЕНӖ">
    <meta property="og:description" content="Реклама в редакции, реклама в газету">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.site.name }}{{ request.path }}">
    <meta property="og:site_name" content="ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета 'Селький труженик'">
    {% if all_advertising.0.image %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.site.name }}/media/{{ all_advertising.0.image }}">
    {% endif %}
{% endblock %}

{% block main %}
<div class="row about">
{% comment %}
    <div class="col-3 about__menu">
        {% include "include_about_menu.html" %}
    </div>
{% endcomment %}
    <div class="col-12 about__content">
        {% for advertising in all_advertising %}
            <div class="news__post">
                <div class="news__header">
                      <span class="news__header-text">{{ advertising.title }}</span>
                </div>
                <div class="news__article-content">{{ advertising.content|safe }}</div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

myapps/about/templates/announcing.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Объявления {% if page %}(страница - {{ page }}){% endif %} / ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета "Селький труженик"{% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><i class="fas fa-home"></i> Главная</li>
        <li class="breadcrumb-item active" aria-current="page">Объявления</li>
    </ol>
</nav>
{% endblock breadcrumb %}

{% block open_graph %}
    <meta property="og:type" content="website" />
    <meta property="og:locale" content="ru_RU">
    <meta property="og:title" content="Объявления на ЯЛ ӖҪЧЕНӖ">
    <meta property="og:description" content="Объявления редакции, Объявления в газету">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.site.name }}{{ request.path }}">
    <meta property="og:site_name" content="ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета 'Селький труженик'">
    {% if all_announcing.0.image %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.site.name }}/media/{{ all_announcing.0.image }}">
    {% endif %}
{% endblock %}

{% block main %}
<div class="row about">
    {% comment %}
    <div class="col-3 about__menu">
        {% include "include_about_menu.html" %}
    </div>
    {% endcomment %}
    <div class="col-12 about__content">
        {% for announcing in all_announcing %}
            {% if announcing.ontop %}
                <div class="news__post">
                    <div class="news__header">
                        <span class="news__header-text">{{ announcing.title }}</span>
                    </div>
                    {% if announcing.image %}
                        {% thumbnail announcing.image "300" crop="center" as im %}
                            <img class="rounded float-left news__post-imgs" alt="" src="{{ im.url }}" data-holder-rendered="true" width="{{ im.width }}" height="{{ im.height }}" loading="lazy">
                        {% endthumbnail %}
                    {% endif %}
                    <div class="news__article-content">{{ announcing.content|safe }}</div>
                    {% if announcing.source %}
                        <div class="news__source">Первоисточник: {{ announcing.source }} </div>
                    {% endif %}
                    <div class="news__created"><i class="far fa-calendar-alt"></i> {{ announcing.publish }}</div>
                </div>
            {% endif %}
        {% endfor %}
        {% for announcing in all_announcing %}
            {% if announcing.ontop is not True %}
                <div class="news__post">
                    <div class="news__header">
                        <span class="news__header-text">{{ announcing.title }}</span>
                    </div>
                    {% if announcing.image %}
                        {% thumbnail announcing.image "300" crop="center" as im %}
                            <img class="rounded float-left news__post-imgs" alt="" src="{{ im.url }}" data-holder-rendered="true" width="{{ im.width }}" height="{{ im.height }}" loading="lazy">
                        {% endthumbnail %}
                    {% endif %}
                    <div class="news__article-content">{{ announcing.content|safe }}</div>
                    {% if announcing.source %}
                        <div class="news__source">Первоисточник: {{ announcing.source }} </div>
                    {% endif %}
                    <div class="news__created"><i class="far fa-calendar-alt"></i> {{ announcing.publish }}</div>
                </div>
            {% endif %}
        {% endfor %}
        {# из myapps.news.templates #}
        {% include "include_paginations.html" with page=all_announcing %}
    </div>
</div>
{% endblock %}

myapps/about/templates/contacts.html
{% extends 'base.html' %}
{% block title %}Контакты / ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета "Селький труженик"{% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><i class="fas fa-home"></i> Главная</li>
    <li class="breadcrumb-item active" aria-current="page">Контакты</li>
  </ol>
</nav>
{% endblock breadcrumb %}

{% block open_graph %}
    <meta property="og:type" content="website" />
    <meta property="og:locale" content="ru_RU">
    <meta property="og:title" content="Контакты ЯЛ ӖҪЧЕНӖ">
    <meta property="og:description" content="Контакты редакции, контакты газеты">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.site.name }}{{ request.path }}">
    <meta property="og:site_name" content="ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета 'Селький труженик'">
    {% if all_contacts.0.image %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.site.name }}/media/{{ all_contacts.0.image }}">
    {% endif %}
{% endblock %}

{% block main %}
    <div class="row about">
        <div class="col-12 about__content">
            {{ all_contacts.items }}
            {% for contacts in all_contacts %}
                <div class="about__title">{{ contacts.title }}</div>
                <div class="contacts-details__post">{{ contacts.content|safe }}</div>
                {% if contacts.map %}
                    {{ contacts.map|safe }}
                {% endif %}
            {% endfor %}
    {% comment %}
        Ссылка на карту (конструктор)
        https://yandex.ru/maps/?um=constructor%3A98308fdfb6d76ece12d73780c3ab9e45d1162b227971510aa97ba97a190135cc&source=constructorLink
    {% endcomment %}
        </div>
    </div>
{% endblock %}

myapps/about/templates/documents.html
{% extends 'base.html' %}
{% block title %}Документы / ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета "Селький труженик"{% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><i class="fas fa-home"></i> Главная</li>
    <li class="breadcrumb-item" aria-current="page">Редакция</li>
    <li class="breadcrumb-item active" aria-current="page">Документы</li>
  </ol>
</nav>
{% endblock breadcrumb %}

{% block open_graph %}
    <meta property="og:type" content="website" />
    <meta property="og:locale" content="ru_RU">
    <meta property="og:title" content="Документы ЯЛ ӖҪЧЕНӖ">
    <meta property="og:description" content="Документы редакции, документы газеты">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.site.name }}{{ request.path }}">
    <meta property="og:site_name" content="ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета 'Селький труженик'">
    {% if all_documents.0.image %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.site.name }}/media/{{ all_documents.0.image }}">
    {% endif %}
{% endblock %}

{% block main %}
<div class="row about">
    {% include "include_about_menu.html" %}
    <div class="col-6 about__content">
            <div class="accordion" id="accordionDocument">
                {% for documents in all_documents %}
                  <div class="card">
                    <div class="card-header" id="heading{{ forloop.counter }}">
                      <h2 class="mb-0">
                        <button class="btn btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapse{{ forloop.counter }}">
                          {{ documents.title }}
                        </button>
                      </h2>
                    </div>

                    <div id="collapse{{ forloop.counter }}" class="collapse" aria-labelledby="heading{{ forloop.counter }}" data-parent="#accordionDocument">
                      <div class="card-body">
                        {% for file in documents.get_subfeature_docs %}
                            <div class="documents-details__filename">
                                <a href="/media/{{ file.file }}" target="_blank">{{ file.filename }}</a> <span class="text-muted font-italic small">({{ file.file.size|filesizeformat }})</span>
                            </div>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                {% endfor %}
            </div>
    </div>
    {% include "include_banners.html" %}
</div>
{% endblock %}

myapps/about/templates/history.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}История редакции / ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета "Селький труженик"{% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><i class="fas fa-home"></i> Главная</li>
        <li class="breadcrumb-item" aria-current="page">Редакция</li>
        <li class="breadcrumb-item active" aria-current="page">История редакции</li>
    </ol>
</nav>
{% endblock breadcrumb %}

{% block open_graph %}
    <meta property="og:type" content="website" />
    <meta property="og:locale" content="ru_RU">
    <meta property="og:title" content="История ЯЛ ӖҪЧЕНӖ">
    <meta property="og:description" content="История редакции, история газеты">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.site.name }}{{ request.path }}">
    <meta property="og:site_name" content="ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета 'Селький труженик'">
    {% if all_history.0.image %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.site.name }}/media/{{ all_history.0.image }}">
    {% endif %}
{% endblock %}

{% block main %}
<div class="row about">
    {% include "include_about_menu.html" %}
    <div class="col-9 about__content">
        {% for history in all_history %}
        <div class="news__post">
            <div class="news__header">
                <span class="news__header-text">{{ history.title }}</span>
            </div>
            {% if history.image %}
            <a href="/media/{{ history.image }}" rel="gallery" class="swipebox" title="{{ history.title }}">
                {% thumbnail history.image "300" crop="center" as im %}
                <img class="rounded float-left news__post-imgs" alt="" src="{{ im.url }}" data-holder-rendered="true" width="{{ im.width }}" height="{{ im.height }}" loading="lazy">
                {% endthumbnail %}
                {% endif %}
            </a>
            <div class="news__article-content text-justify">{{ history.content|safe }}</div>
            <div class="news__created"><i class="far fa-calendar-alt"></i> {{ history.publish }}</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

myapps/about/templates/include_about_menu.html
<div class="col-3 about__menu">
    <div class="list-group list-group-flush">
      <a href="{% url 'about:structure' %}" class="list-group-item list-group-item-action">Структура</a>
      <a href="{% url 'about:vacancies' %}" class="list-group-item list-group-item-action">Вакансии</a>
      <a href="{% url 'about:documents' %}" class="list-group-item list-group-item-action">Документы</a>
      <a href="{% url 'about:projects' %}" class="list-group-item list-group-item-action">Проекты</a>
      <a href="{% url 'about:history' %}" class="list-group-item list-group-item-action">История редакции</a>
    </div>
</div>

myapps/about/templates/projects.html
{% extends 'base.html' %}
{% block title %}Проекты / ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета "Селький труженик"{% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><i class="fas fa-home"></i> Главная</li>
    <li class="breadcrumb-item" aria-current="page">Редакция</li>
    <li class="breadcrumb-item active" aria-current="page">Проекты</li>
  </ol>
</nav>
{% endblock breadcrumb %}

{% block open_graph %}
    <meta property="og:type" content="website" />
    <meta property="og:locale" content="ru_RU">
    <meta property="og:title" content="Проекты ЯЛ ӖҪЧЕНӖ">
    <meta property="og:description" content="Проекты редакции, Проекты газеты">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.site.name }}{{ request.path }}">
    <meta property="og:site_name" content="ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета 'Селький труженик'">
    {% if all_projects.0.image %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.site.name }}/media/{{ all_projects.0.image }}">
    {% endif %}
{% endblock %}

{% block main %}
<div class="row about">
    {% include "include_about_menu.html" %}
    <div class="col-6 about__content">
            <div class="accordion" id="accordionDocument">
                {% for projects in all_projects %}
                  <div class="card">
                    <div class="card-header" id="heading{{ forloop.counter }}">
                      <h2 class="mb-0">
                        <button class="btn btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapse{{ forloop.counter }}">
                          {{ projects.title }}
                        </button>
                      </h2>
                    </div>

                    <div id="collapse{{ forloop.counter }}" class="collapse" aria-labelledby="heading{{ forloop.counter }}" data-parent="#accordionDocument">
                      <div class="card-body">
                        {% for file in projects.get_subfeature_docs %}
                            <div class="projects-details__filename">
                                <a href="/media/{{ file.file }}" target="_blank">{{ file.filename }}</a> <span class="text-muted font-italic small">({{ file.file.size|filesizeformat }})</span>
                            </div>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                {% endfor %}
            </div>
    </div>
    {% include "include_banners.html" %}
</div>
{% endblock %}

myapps/about/templates/structure.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Структура / ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета "Селький труженик" {% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><i class="fas fa-home"></i> Главная</li>
    <li class="breadcrumb-item" aria-current="page">Редакция</li>
    <li class="breadcrumb-item active" aria-current="page">Структура</li>
  </ol>
</nav>
{% endblock breadcrumb %}

{% block open_graph %}
    <meta property="og:type" content="website" />
    <meta property="og:locale" content="ru_RU">
    <meta property="og:title" content="Структура ЯЛ ӖҪЧЕНӖ">
    <meta property="og:description" content="Структура редакции, работники газеты">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.site.name }}{{ request.path }}">
    <meta property="og:site_name" content="ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета 'Селький труженик'">
    {% if all_employees.0.photo %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.site.name }}/media/{{ all_employees.0.photo }}">
    {% endif %}
{% endblock %}

{% block main %}
<div class="row about">
    {% include "include_about_menu.html" %}
    <div class="col-9 about__content">
        {% for employee in all_employees %}
            <div class="row employee">
                <div class="col-3 employee-photo">
                    {% thumbnail employee.photo "140" crop="center" as im %}
                      <img class="w-100 rounded-circle" alt="{{ employee.name }}" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" loading="lazy">
                    {% endthumbnail %}
                </div>
                <div class="col-8 employee-details">
                    <div class="employee__detail font-weight-bold">{{ employee.name }}</div>
                    <div class="employee-detail"><i class="far fa-address-card"></i> {{ employee.post }}</div>
                    <div class="employee-detail"><i class="fas fa-phone"></i> <a href="tel:{{ employee.phone|cut:" "|cut:")"|cut:"("|cut:"-"}}">{{ employee.phone }}</a></div>
                    {% if employee.email %}
                        <div class="employee-detail"><i class="fas fa-at"></i> <a href="mailto:{{ employee.email }}">{{ employee.email }}</a></div>

                    {% endif %}
                    {% if employee.education %}
                        <div class="employee-detail"><i class="fas fa-university"></i> {{ employee.education }}</div>
                    {% endif %}
                    {% if employee.bio %}
                        <div class="employee-detail"><i class="fas fa-info-circle"></i> {{ employee.bio }}</div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

myapps/about/templates/subscribe.html
{% extends 'base.html' %}
{% block title %}Подписка / ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета "Селький труженик"{% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><i class="fas fa-home"></i> Главная</li>
    <li class="breadcrumb-item active" aria-current="page">Подписка</li>
  </ol>
</nav>
{% endblock breadcrumb %}

{% block open_graph %}
    <meta property="og:type" content="website" />
    <meta property="og:locale" content="ru_RU">
    <meta property="og:title" content="Подписка на газету ЯЛ ӖҪЧЕНӖ">
    <meta property="og:description" content="Подписка в редакции, подписка на газету">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.site.name }}{{ request.path }}">
    <meta property="og:site_name" content="ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета 'Селький труженик'">
    {% if all_subscribe.0.image %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.site.name }}/media/{{ all_subscribe.0.image }}">
    {% endif %}
{% endblock %}

{% block main %}
<div class="row about">
{% comment %}
    <div class="col-3 about__menu">
        {% include "include_about_menu.html" %}
    </div>
{% endcomment %}
    <div class="col-12 about__content">
        {% for subscribe in all_subscribe %}
            <div class="news__post">
                <div class="news__header">
                      <span class="news__header-text">{{ subscribe.title }}</span>
                </div>
                <div class="news__article-content">{{ subscribe.content|safe }}</div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

myapps/about/templates/vacancies.html
{% extends 'base.html' %}
{% block title %}Вакансии / ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета "Селький труженик"{% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><i class="fas fa-home"></i> Главная</li>
    <li class="breadcrumb-item" aria-current="page">Редакция</li>
    <li class="breadcrumb-item active" aria-current="page">Вакансии</li>
  </ol>
</nav>
{% endblock breadcrumb %}

{% block open_graph %}
    <meta property="og:type" content="website" />
    <meta property="og:locale" content="ru_RU">
    <meta property="og:title" content="Вакансии ЯЛ ӖҪЧЕНӖ">
    <meta property="og:description" content="Вакансии редакции, вакансии газеты">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.site.name }}{{ request.path }}">
    <meta property="og:site_name" content="ЯЛ ӖҪЧЕНӖ - Янтиковская районная газета 'Селький труженик'">
    {% if all_vacancies.0.image %}
        <meta property="og:image" content="{{ request.scheme }}://{{ request.site.name }}/media/{{ all_vacancies.0.image }}">
    {% endif %}
{% endblock %}

{% block main %}
<div class="row about">
    {% include "include_about_menu.html" %}
    <div class="col-6 about__content">
            <div class="accordion" id="accordionVacancy">
                {% for vacancy in all_vacancies %}
                  <div class="card">
                    <div class="card-header" id="heading{{ forloop.counter }}">
                      <h2 class="mb-0">
                        <button class="btn btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapse{{ forloop.counter }}">
                          {{ vacancy.post }}
                        </button>
                      </h2>
                    </div>

                    <div id="collapse{{ forloop.counter }}" class="collapse" aria-labelledby="heading{{ forloop.counter }}" data-parent="#accordionVacancy">
                      <div class="card-body">
                        {{ vacancy.content|safe }}
                      </div>
                    </div>
                  </div>
                {% endfor %}
            </div>
    </div>
    {# из myapps.news.templates #}
    {% include "include_banners.html" %}
</div>
{% endblock %}